CREATE DATABASE PADELTADB
GO

USE PADELTADB

CREATE TABLE Usuarios(
Username VARCHAR(30) PRIMARY KEY NOT NULL,
Nombre VARCHAR(30),
Apellido1 VARCHAR(30),
Apellido2 VARCHAR(30),
Correo VARCHAR(80) UNIQUE NOT NULL,
Contrasena VARCHAR(30)
);

CREATE TABLE Productos(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
Description VARCHAR(255),
Image VARCHAR(100),
Price DECIMAL(10, 2) NOT NULL,
Discount INT,
Category VARCHAR(30),
Active BIT NOT NULL,
Stock INT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);