CREATE DATABASE PADELTADB
GO

USE PADELTADB

CREATE TABLE Usuarios(
Username VARCHAR(30) PRIMARY KEY NOT NULL,
Nombre VARCHAR(30),
Apellido1 VARCHAR(30),
Apellido2 VARCHAR(30),
Correo VARCHAR(80) UNIQUE NOT NULL,
Contrasena VARCHAR(30)
);