CREATE DATABASE PADELTADB
GO

USE PADELTADB

CREATE TABLE Usuarios(
Username VARCHAR(30) PRIMARY KEY NOT NULL,
Nombre VARCHAR(30),
Apellido1 VARCHAR(30),
Apellido2 VARCHAR(30),
Correo VARCHAR(80) UNIQUE NOT NULL,
Contrasena VARCHAR(30)
);

CREATE TABLE Productos(
Id uniqueidentifier PRIMARY KEY not null DEFAULT NEWID(),
Name VARCHAR(50) NOT NULL,
Description VARCHAR(255),
Price DECIMAL(10, 2) NOT NULL,
Discount INT,
Category VARCHAR(30),
Active BIT NOT NULL,
Stock INT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Imagen(
Id uniqueidentifier PRIMARY KEY not null DEFAULT NEWID(),
ProductoId uniqueidentifier NOT NULL,
Name VARCHAR(100) NOT NULL,
FOREIGN KEY (ProductoId) REFERENCES Productos(Id)
);